# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music_streaming.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'music_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15music_streaming.proto\x12\x0emusicstreaming\"\x07\n\x05\x45mpty\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x1d\n\x0fPlaylistRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\x0bSongRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"0\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"E\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\x05\x12\x0f\n\x07songIds\x18\x04 \x03(\x05\"/\n\x08UserList\x12#\n\x05users\x18\x01 \x03(\x0b\x32\x14.musicstreaming.User\"/\n\x08SongList\x12#\n\x05songs\x18\x01 \x03(\x0b\x32\x14.musicstreaming.Song\";\n\x0cPlaylistList\x12+\n\tplaylists\x18\x01 \x03(\x0b\x32\x18.musicstreaming.Playlist2\x80\x03\n\x0cMusicService\x12<\n\tListUsers\x12\x15.musicstreaming.Empty\x1a\x18.musicstreaming.UserList\x12<\n\tListSongs\x12\x15.musicstreaming.Empty\x1a\x18.musicstreaming.SongList\x12P\n\x13ListPlaylistsByUser\x12\x1b.musicstreaming.UserRequest\x1a\x1c.musicstreaming.PlaylistList\x12P\n\x13ListSongsByPlaylist\x12\x1f.musicstreaming.PlaylistRequest\x1a\x18.musicstreaming.SongList\x12P\n\x13ListPlaylistsBySong\x12\x1b.musicstreaming.SongRequest\x1a\x1c.musicstreaming.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_USERREQUEST']._serialized_start=50
  _globals['_USERREQUEST']._serialized_end=75
  _globals['_PLAYLISTREQUEST']._serialized_start=77
  _globals['_PLAYLISTREQUEST']._serialized_end=106
  _globals['_SONGREQUEST']._serialized_start=108
  _globals['_SONGREQUEST']._serialized_end=133
  _globals['_USER']._serialized_start=135
  _globals['_USER']._serialized_end=180
  _globals['_SONG']._serialized_start=182
  _globals['_SONG']._serialized_end=230
  _globals['_PLAYLIST']._serialized_start=232
  _globals['_PLAYLIST']._serialized_end=301
  _globals['_USERLIST']._serialized_start=303
  _globals['_USERLIST']._serialized_end=350
  _globals['_SONGLIST']._serialized_start=352
  _globals['_SONGLIST']._serialized_end=399
  _globals['_PLAYLISTLIST']._serialized_start=401
  _globals['_PLAYLISTLIST']._serialized_end=460
  _globals['_MUSICSERVICE']._serialized_start=463
  _globals['_MUSICSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
