# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_streaming_pb2 as music__streaming__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in music_streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/musicstreaming.MusicService/ListUsers',
                request_serializer=music__streaming__pb2.Empty.SerializeToString,
                response_deserializer=music__streaming__pb2.UserList.FromString,
                _registered_method=True)
        self.ListSongs = channel.unary_unary(
                '/musicstreaming.MusicService/ListSongs',
                request_serializer=music__streaming__pb2.Empty.SerializeToString,
                response_deserializer=music__streaming__pb2.SongList.FromString,
                _registered_method=True)
        self.ListPlaylistsByUser = channel.unary_unary(
                '/musicstreaming.MusicService/ListPlaylistsByUser',
                request_serializer=music__streaming__pb2.UserRequest.SerializeToString,
                response_deserializer=music__streaming__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.ListSongsByPlaylist = channel.unary_unary(
                '/musicstreaming.MusicService/ListSongsByPlaylist',
                request_serializer=music__streaming__pb2.PlaylistRequest.SerializeToString,
                response_deserializer=music__streaming__pb2.SongList.FromString,
                _registered_method=True)
        self.ListPlaylistsBySong = channel.unary_unary(
                '/musicstreaming.MusicService/ListPlaylistsBySong',
                request_serializer=music__streaming__pb2.SongRequest.SerializeToString,
                response_deserializer=music__streaming__pb2.PlaylistList.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSongs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylistsByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlaylistsBySong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=music__streaming__pb2.Empty.FromString,
                    response_serializer=music__streaming__pb2.UserList.SerializeToString,
            ),
            'ListSongs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSongs,
                    request_deserializer=music__streaming__pb2.Empty.FromString,
                    response_serializer=music__streaming__pb2.SongList.SerializeToString,
            ),
            'ListPlaylistsByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylistsByUser,
                    request_deserializer=music__streaming__pb2.UserRequest.FromString,
                    response_serializer=music__streaming__pb2.PlaylistList.SerializeToString,
            ),
            'ListSongsByPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSongsByPlaylist,
                    request_deserializer=music__streaming__pb2.PlaylistRequest.FromString,
                    response_serializer=music__streaming__pb2.SongList.SerializeToString,
            ),
            'ListPlaylistsBySong': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlaylistsBySong,
                    request_deserializer=music__streaming__pb2.SongRequest.FromString,
                    response_serializer=music__streaming__pb2.PlaylistList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'musicstreaming.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('musicstreaming.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicstreaming.MusicService/ListUsers',
            music__streaming__pb2.Empty.SerializeToString,
            music__streaming__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSongs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicstreaming.MusicService/ListSongs',
            music__streaming__pb2.Empty.SerializeToString,
            music__streaming__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylistsByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicstreaming.MusicService/ListPlaylistsByUser',
            music__streaming__pb2.UserRequest.SerializeToString,
            music__streaming__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSongsByPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicstreaming.MusicService/ListSongsByPlaylist',
            music__streaming__pb2.PlaylistRequest.SerializeToString,
            music__streaming__pb2.SongList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlaylistsBySong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/musicstreaming.MusicService/ListPlaylistsBySong',
            music__streaming__pb2.SongRequest.SerializeToString,
            music__streaming__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
